### ISSUE TITLE
[Clarification] Issue Field History restarted to To Do status after resolved

### ISSUE THREAD

**Issue by dennysrega1ado** [fivetran/dbt_jira#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Since I could not find the Fivetran community forum, I posted this issue here.
Why does the `issue_field_history` table continue recording "changes" if the issue has already been closed?
It seems like the status was reset to `To Do` status.

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/f17d4b61-56a6-4a8b-8baf-67d2d6041e96">

### Relevant error log or model output

```shell
n/a
```

### Expected behavior

I expect the `issue_field_history` to stop recording the issue since the ticket status has not changed.

### dbt Project configurations

```yaml
  jira:
    +schema: fivetran_jira
```

### Package versions

```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: brooklyn-data/dbt_artifacts
    version: 2.2.2
  - package: data-mie/dbt_profiler
    version: 0.8.1
  - package: fivetran/zendesk
    version: 0.12.0
  - package: dbt-labs/audit_helper
    version: 0.7.0
  - package: get-select/dbt_snowflake_monitoring
    version: 5.0.3
  - package: fivetran/jira_source
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/jira
    version: [">=0.17.0", "<0.18.0"]


```

### What database are you using dbt with?

snowflake

### dbt Version

```bash
root@82b6a9e763a1:/app/data_marts# dbt --version
Core:
  - installed: 1.6.9
```

### Additional Context

We are running  DBT CLI in AWS ECS

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
