### ISSUE TITLE
BUG - new field values not being reflected in `jira__issue_enhanced` on incremental runs

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_jira#41]
**Are you a current Fivetran customer?** 

nope but this came from https://getdbt.slack.com/archives/C01D1R2JLLA/p1635355824026800 

**Describe the bug**

on incremental runs of the package, if you have removed (or changed ? -- asking Jacob this...) a field value, the new value is not being reflected in the issue enhanced model

**Steps to reproduce**
1. create a ticket and add label
2. sync fivetran 
3. execute incremental run
4. confirm the label value is there in `jira__issue_enhanced`
5. remove the label in jira
6. resync
7. execute incremental run
8. if you still see the old label value, run a full refresh and see if it works _now_

**Expected behavior**

the model should pick up the new changes on an incremental run, full refreshes or materializing as tables should not be required

**Project variables configuration**

```yml
vars:
  jira_database: raw
  jira_schema: jira_fivetran
  jira:
    # Field options can be found with this query:
    # select name from RAW.JIRA_FIVETRAN.FIELD;
    issue_field_history_columns: ['Labels', 'Key', 'Epic Name', 'Severity', 'Project']

  'dbt_date:time_zone': 'America/New_York'
  dbt_artifacts:
    dbt_artifacts_database: analytics
    dbt_artifacts_schema: dbt_artifacts
    dbt_artifacts_table: artifacts
```

**Package Version**

```yml
copy packages.yml here
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 
this [line](https://github.com/fivetran/dbt_jira/blob/master/models/intermediate/field_history/int_jira__agg_multiselect_history.sql#L22) may be an issue -- we're subtracting 1 day from the wrong side i think (so like we should do this to max(date_day) from {{ this }} instead of when the field was updated_at . i think this would cause the package to ignore the most recent day of data on incremental runs. 

otherwise, the problem may live in the [pivot model](https://github.com/fivetran/dbt_jira/blob/master/models/intermediate/field_history/int_jira__pivot_daily_field_history.sql) or the [final daily issue field history model](https://github.com/fivetran/dbt_jira/blob/master/models/jira__daily_issue_field_history.sql)

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
