### ISSUE TITLE
[Bug] Invalid column name in issue_field_history_columns 

### ISSUE THREAD

**Issue by crowemi** [fivetran/dbt_jira#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When using the `issue_field_history_columns` with a column having a leading numeric character in the name, the package fails. E.g. column name "1st reply date"

### Relevant error log or model output

```shell
23:23:22  Database Error in model int_jira__pivot_daily_field_history (models/intermediate/field_history/int_jira__pivot_daily_field_history.sql)
23:23:22    001003 (42000): SQL compilation error:
23:23:22    syntax error line 29 at position 110 unexpected '1'.
23:23:22    compiled SQL at target/run/jira/models/intermediate/field_history/int_jira__pivot_daily_field_history.sql
```

### Expected behavior

I expect the packages to succeed and create a column for the custom field in the `jira__issues_enhanced` and `jira__daily_issue_field_history` models with the corresponding values from the custom field.

### dbt Project configurations

``` yaml
vars:
  # jira settings
  jira_database: <database>
  jira_schema: jira
  jira_using_sprints: false
  jira_using_components: false
  issue_field_history_columns: [
    '1st reply date'
  ]
```

### Package versions

``` yaml
  - package: fivetran/jira
    version: 0.8.2
  - package: fivetran/jira_source
    version: 0.4.2
```

### What database are you using dbt with?

snowflake

### dbt Version

1.2.0

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
